-- DELETE tables
DROP TABLE IF EXISTS weather;
DROP TABLE IF EXISTS transportation;
DROP TABLE IF EXISTS expense;
DROP TABLE IF EXISTS hotel_rating;
DROP TABLE IF EXISTS restaurant_rating;
DROP TABLE IF EXISTS city_rating;
DROP TABLE IF EXISTS souvenir;
DROP TABLE IF EXISTS languages;
DROP TABLE IF EXISTS restaurant_discount;
DROP TABLE IF EXISTS hotel_discount;
DROP TABLE IF EXISTS currency_exchange;
DROP TABLE IF EXISTS restaurant;
DROP TABLE IF EXISTS hotel;
DROP TABLE IF EXISTS travel;
DROP TABLE IF EXISTS city;
DROP TABLE IF EXISTS country;
DROP DATABASE IF EXISTS team18;